id: PEEE5BD6A
initial_creation_type: input
source_metadata:
  title: Termas
  language: de
  description: 'A collection of spiritual treasures or terma (gter ma), which were
    reportedly hidden by Guru Padmasambhava and Yeshe Tsogyal, either in the earth
    and in the minds of disciples, and then revealed at the appropriate time by ‘treasure
    revealers’ or tertön (gter ston):'
  volume:
    4a1cfa4da6f543f28d5b73205694a081:
      title: Daily Practice of Vajrakīla
      parent: Apang Tertön
    7e2ff1b82ebc4622aa68e013a3fd7b78:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Chöje Lingpa
    c35afabcaa1743d68abd70ccbd701c30:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Chöje Lingpa
    3b490b02118b4f4b94e65cf4c83f4932:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Chokgyur Dechen Lingpa
    c2c3cf3a680745d287e95309c481d21d:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Chokgyur Dechen Lingpa
    2d9ed4800d4145cd84103fb4d9db8951:
      title: The Lament of Rudra
      parent: Chokgyur Dechen Lingpa
    9e1b7c51494c488f934283c2ee52f47d:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    1d4e0222715a4803a603fa9c1c48ba90:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    39b7244cf95048e7be2c467a566d5db8:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    8909af26a34e4c26a8378a51c267b55b:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    44bb61e03fee41ac8f0659a776594e6e:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    f084f5f02dd349a0a3dd6c6bc5b80d4c:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Chokgyur Dechen Lingpa
    6cfc3460ae4b4db0a9baab01b4c0c614:
      title: Concise Daily Practice of Vajrasattva
      parent: Chokgyur Dechen Lingpa
    81f9709ac8c14dcca45c120687caa927:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chokgyur Dechen Lingpa
    5c3530faadcb47ac8237281cd2241a6e:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    798f4bbd95314979b61868bfb22ca9ac:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Do Khyentse
    f5700056db6c4972bcbfddf313554535:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    f47e6ee9f20844b6ab416d62a109c97a:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Do Khyentse
    ec99b31c0b9143688d7fa0ab18e1ce64:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Do Khyentse
    ef52a854b57f4c729e57b5ad440ca112:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    70da2c3154974920bc8ec142d86f3b7a:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Dorje Dechen Lingpa
    4ed167c332e1436c854c4e3b06a7b90b:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Dudjom Lingpa
    e885fe92c38442ee88fd16604c66638b:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Dudjom Rinpoche
    7af72396b08049f498c0bf2c4c39c455:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    01a42f064da8424c898f599a9ec1a501:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Guru Chöwang
    bbd8cffaf9a24696a96a40a02d2ad561:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Guru Chöwang
    5d9bc03a03d945bda7bbd853f3955ce7:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Guru Chöwang
    5f4df502dcf94fa0847501a5fb11ae46:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Guru Chöwang
    a77e4da39d944532afb0097a2131a88a:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Guru Chöwang
    f2b0ef7c910545eaa6a5149da13e49f5:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Guru Chöwang
    c94d55074ba24109b1ba992486e45932:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Gyarong Khandro
    7ce5e3f6b4d242359b93c9b01761b23a:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Jamyang Khyentse Chökyi Lodrö
    2b172ce0e94e476185463e0c3aceff12:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    96755c55939c4173b1ef8851370dfc1f:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Jamyang Khyentse Wangpo
    42ad7132ae6c42adb3e2638e33dc76bb:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    46b9bf3372484e20a6671549625df525:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Jamyang Khyentse Wangpo
    48853a8683684a258e201c98cae5c358:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Jatsön Nyingpo
    9232ed2665dc40f5acfdd4705205ee3a:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Jatsön Nyingpo
    b19e73f330f74497ab311f864faa5639:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Jigdral Tutop Lingpa
    bdbc742d6f32466590a75fb2cd8d6bfd:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Jigme Lingpa
    4eb9016c656e4425bda7c702198c63ac:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    34a5f4ae246e43499015d0c16cf7e493:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    d179c347a91447049fbdc3c9b72ee6c6:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Jigme Lingpa
    eeb2de8ea1634342a2b4377067b429c8:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Jigme Lingpa
    2a7a8fc778fc4f9b84791548ecd75e4d:
      title: Brief Prayer of the Feast Gathering
      parent: Jigme Lingpa
    2feffc40f14f46a2b942103899c84ef2:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    73a8368b40b94dbd9f24847b3949993d:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Jigme Lingpa
    415814aed9db40d49695901e81216eb5:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Jigme Lingpa
    d64fb0faadbe4581a621dedc4a749cba:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Jigme Lingpa
    8b5b868de0ea4bb0b9ec9d4322d31a8d:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Jigme Lingpa
    fee4446615814e9c9f66ccf851f22669:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Jigme Lingpa
    7b6fe04d631b4cde9907618c6d297ca8:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Jigme Lingpa
    2defb48083444eca8c6d987f17c26d5a:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Jigme Lingpa
    d846b5a60005494bb54cf5ca1e7a83ad:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Jigme Lingpa
    596de98c1fe64edcab84d72a6a42db4a:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Jigme Lingpa
    80538511501c4156a41ae5cfd17add54:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Jigme Lingpa
    693922fb3675486c82f51135c2d27229:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Jigme Lingpa
    8231e84d83e24934ac1b366caac5c08f:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Jigme Lingpa
    c08d95712f9544f1873226d5903ced03:
      title: Vajra Verses on the Natural State
      parent: Jigme Lingpa
    6cf3bd4b0d0547fe846c1f9d6759cea0:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Karma Lingpa
    2ec975cece6b49d69514c08e0ec5d2ee:
      title: The Benefits of the Vajra Guru Mantra and an Explanation of Its Syllables
      parent: Karma Lingpa
    afac81c0a3154306a7991e86e2e79d20:
      title: The Root Verses on the Six Bardos
      parent: Karma Lingpa
    bcceaedfa9a74109a7adde5330f1fa04:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Khenchen Jigme Phuntsok
    7788002d3ac14097846d9fbda199306f:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Khenchen Jigme Phuntsok
    2f81fe403bac488c8bc034ae1024c3d3:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Lhatsün Namkha Jigme
    8ddef56e12f840f1bf87c263e693f2df:
      title: Maṇḍala Offering from Longsal Dorje Nyingpo
      parent: Longsal Nyingpo
    e6e61533a89f4a278939e3208e7379bd:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Ngakchang Shakya Zangpo
    86c41b3aab994d60855bc3c93fc79242:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Nyala Pema Dündul
    50e2d8fe03494673869148467421437e:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    0dd5eb6ae2374b87bfa53624ade5f5fe:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    176f82d67c584870b628ae9458e6e52f:
      title: The Pointing-the-Staff Instruction
      parent: Nyang Ral Nyima Özer
    aa3706110fde4d99b2394590c92af29e:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: Orgyen Lingpa
    5ea09982f96f4104bbe5c8a2aa405bc3:
      title: Yeshe Tsogyal's Prayer
      parent: Pema Lingpa
    b5d6bebbcbd24c5f85104b81a27aadc5:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Ratna Lingpa
    1a23d69c4cbb469b957502a6437dab48:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Rigdzin Gödem
    aeb3323d4be64363bc03fccf0d1a072c:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Rigdzin Gödem
    a6b4088573bf411ab65546fbcc2f1509:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Rigdzin Nyima Drakpa
    ea4a949d86a34378abcc9c3378280c21:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Samten Lingpa
    2fea153025b6457d9d9ccca15522d927:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sera Khandro
    87ba935b43dc4ccd9ab25959c8914321:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sera Khandro
    9e70d267cdc742e5aebe96159d112a08:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Sherab Özer
    a14211f01ec74e629c0ec8756c9c24a1:
      title: Brief Sukhāvatī Aspiration
      parent: Tertön Mingyur Dorje
    cbf63d1124014981bdcf51ed87392dcf:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Tertön Mingyur Dorje
    cbb506b363a646e2a04efb672ac10c52:
      title: Prayer to Behold Amitābha in Dreams
      parent: Tertön Mingyur Dorje
    5d91c25e4c3e4eb0bc3157dca9cdb711:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Tertön Sogyal
    ae4f549251a545afa134c942ed65ea64:
      title: Sādhana of Mañjughoṣa
      parent: Tertön Sogyal
    832e60f95a41467da2867df68fbb49b2:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Tertön Sogyal
    6dfa15964ca44461bfd7a2aed2a664b1:
      title: The Guru Yoga of the Profound Path
      parent: Tertön Sogyal
    4bbefba30bd34f9999d44d8fe9ce7e05:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Tertön Sogyal
    aedfde33752b410ba3e9c617323d902c:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Tertön Sogyal
    a2886dc51d4346c09cd6d660b03b48d7:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Tertön Sogyal
    349e4ba6240241168dc527ca0df80145:
      title: The Wisdom Mind Practice of One Kīla
      parent: Tertön Sogyal
    259098faf0a44bff9c6787b7131d33f0:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Tulku Zangpo Drakpa
    2c96edc46edc4a2590366cda55255187:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Tulku Zangpo Drakpa
    2b2b473f5d90477bb903d34ec848549b:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Tulku Zangpo Drakpa
    edb199c5de964fb4854a98c45c07b238:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Tulku Zangpo Drakpa
    3ed2dc14d3664e2690adbeda91168cdf:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Tulku Zangpo Drakpa
    f2f2b95f0ad5490b95fd1399d1bda5a6:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Tulku Zangpo Drakpa
    efeb26cefb034549906a6c25af4103a1:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Tulku Zangpo Drakpa
    2598d9a2d54b49068da1a39f8e93d19c:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Tulku Zangpo Drakpa
created_at: '2022-03-01T06:17:48.620537'
last_modified_at: '2022-03-01T06:17:48.620541'
